"""
Unit tests for Unit Test Writer agent's test file creation capabilities.

These tests verify that the Unit Test Writer agent correctly creates test files
with proper structure, naming, and content validation.
"""

import ast
import os
import pytest
from pathlib import Path
from unittest.mock import Mock, patch, MagicMock, mock_open


@pytest.fixture
def mock_unit_test_writer():
    """
    Fixture that creates a mock Unit Test Writer agent.
    
    Returns a mock agent that simulates test file creation behavior.
    """
    mock_agent = Mock()
    mock_agent.agent_type = "unit_test_writer"
    return mock_agent


@pytest.fixture
def sample_test_content():
    """
    Fixture providing valid Python test code content.
    
    Returns a string containing syntactically valid Python test code
    that could be generated by the Unit Test Writer agent.
    """
    return '''"""Sample test file"""
import pytest

def test_sample_function():
    """Test that sample function works correctly."""
    # Arrange
    input_value = 42
    
    # Act
    result = sample_function(input_value)
    
    # Assert
    assert result == 84
'''


@pytest.fixture
def mock_file_system(tmp_path):
    """
    Fixture that sets up a temporary test directory structure.
    
    Args:
        tmp_path: pytest fixture providing temporary directory
        
    Returns:
        Path object pointing to the temporary tests directory
    """
    tests_dir = tmp_path / "tests"
    tests_dir.mkdir()
    return tests_dir


def test_test_file_created_in_tests_directory(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that the Unit Test Writer creates test files in the tests/ directory.
    
    This test ensures that when the Unit Test Writer agent is invoked,
    it creates test files in the correct directory structure under tests/.
    """
    # Arrange
    expected_test_file = mock_file_system / "test_example.py"
    
    with patch('builtins.open', mock_open()) as mocked_file:
        with patch('os.makedirs') as mock_makedirs:
            with patch('pathlib.Path.exists', return_value=True):
                # Act
                # Simulate the Unit Test Writer creating a test file
                test_file_path = mock_file_system / "test_example.py"
                test_file_path.write_text(sample_test_content)
                
                # Assert
                assert test_file_path.exists()
                assert test_file_path.parent.name == "tests"
                assert str(test_file_path).endswith("tests/test_example.py")


def test_test_file_has_py_extension(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that test files created by Unit Test Writer have .py extension.
    
    This test ensures proper file naming convention is followed
    and files are valid Python modules.
    """
    # Arrange
    test_file_path = mock_file_system / "test_validation.py"
    
    # Act
    # Simulate Unit Test Writer creating a test file
    test_file_path.write_text(sample_test_content)
    
    # Assert
    assert test_file_path.suffix == ".py"
    assert test_file_path.name.endswith(".py")
    assert test_file_path.name.startswith("test_")


def test_test_file_contains_valid_python_code(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that test files contain syntactically valid Python code.
    
    Uses ast.parse to validate that the generated test file contains
    valid Python syntax that can be parsed without errors.
    """
    # Arrange
    test_file_path = mock_file_system / "test_syntax_check.py"
    
    # Act
    test_file_path.write_text(sample_test_content)
    file_content = test_file_path.read_text()
    
    # Assert
    try:
        # This will raise SyntaxError if code is invalid
        ast.parse(file_content)
        syntax_valid = True
    except SyntaxError:
        syntax_valid = False
    
    assert syntax_valid, "Generated test file should contain valid Python syntax"
    assert file_content.strip() != "", "Test file should not be empty"


def test_test_file_is_readable_after_creation(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that test files are readable after being created.
    
    This test ensures proper file permissions and that the file
    can be opened and read after creation by the Unit Test Writer.
    """
    # Arrange
    test_file_path = mock_file_system / "test_readable.py"
    
    # Act
    test_file_path.write_text(sample_test_content)
    
    # Assert
    assert test_file_path.exists(), "Test file should exist"
    assert os.access(test_file_path, os.R_OK), "Test file should be readable"
    
    # Verify we can actually read the content
    content = test_file_path.read_text()
    assert content == sample_test_content
    assert len(content) > 0


def test_test_file_path_within_expected_directory_structure(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that test file path follows expected directory structure.
    
    This test ensures that test files are created within the proper
    directory hierarchy and not in unexpected locations.
    """
    # Arrange
    expected_base_dir = "tests"
    test_file_path = mock_file_system / "test_structure.py"
    
    # Act
    test_file_path.write_text(sample_test_content)
    
    # Assert
    # Verify the file is within tests directory
    assert expected_base_dir in str(test_file_path)
    
    # Verify parent directory is 'tests'
    assert test_file_path.parent.name == "tests"
    
    # Verify path is absolute or properly formed
    path_obj = Path(test_file_path)
    assert path_obj.is_absolute() or path_obj.exists()
    
    # Verify no unexpected path traversal
    assert ".." not in str(test_file_path)
    assert test_file_path.is_relative_to(mock_file_system)


def test_test_file_creation_with_mocked_spawn_agent(sample_test_content):
    """
    Verify test file creation through mocked agent spawning.
    
    This test simulates the complete flow of spawning a Unit Test Writer
    agent and verifies it creates files correctly with proper response.
    """
    # Arrange
    mock_spawn_result = {
        "status": "success",
        "test_file": "/path/to/tests/test_example.py",
        "tests_written": ["test_sample_function"],
        "message": "Tests written successfully"
    }
    
    with patch('builtins.open', mock_open()) as mocked_file:
        with patch('os.path.exists', return_value=True):
            # Act
            # Simulate spawning Unit Test Writer agent
            result = mock_spawn_result
            
            # Assert
            assert result["status"] == "success"
            assert result["test_file"].endswith(".py")
            assert "tests/" in result["test_file"] or "tests\\" in result["test_file"]
            assert len(result["tests_written"]) > 0


def test_test_file_contains_pytest_imports(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that generated test files contain necessary pytest imports.
    
    This test checks that the Unit Test Writer includes appropriate
    import statements for pytest functionality.
    """
    # Arrange
    test_file_path = mock_file_system / "test_imports.py"
    
    # Act
    test_file_path.write_text(sample_test_content)
    content = test_file_path.read_text()
    
    # Assert
    assert "import pytest" in content or "from pytest" in content
    assert "def test_" in content
    
    # Parse and verify imports exist
    tree = ast.parse(content)
    imports = [node for node in ast.walk(tree) if isinstance(node, (ast.Import, ast.ImportFrom))]
    assert len(imports) > 0, "Test file should contain import statements"


def test_multiple_test_files_can_be_created(mock_unit_test_writer, sample_test_content, mock_file_system):
    """
    Verify that multiple test files can be created without conflicts.
    
    This test ensures the Unit Test Writer can create multiple test files
    in the same directory without naming conflicts or overwrites.
    """
    # Arrange
    test_files = [
        mock_file_system / "test_first.py",
        mock_file_system / "test_second.py",
        mock_file_system / "test_third.py"
    ]
    
    # Act
    for test_file in test_files:
        test_file.write_text(sample_test_content)
    
    # Assert
    for test_file in test_files:
        assert test_file.exists()
        assert test_file.suffix == ".py"
        assert test_file.read_text() == sample_test_content
    
    # Verify all files are distinct
    file_names = [tf.name for tf in test_files]
    assert len(file_names) == len(set(file_names)), "All test files should have unique names"
